### PR TITLE
added missing commons-lang3 library and project files for IDEA

### LINKED ISSUE #66: Unable to build 1.6.0 on Windows
@firewave I am unable to build the current `master` branch on Windows with IntelliJ 2021.3. The compile errors I get:

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:14:32
java: package org.apache.commons.lang3 does not exist
```

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:57:48
java: cannot find symbol
  symbol:   variable RandomStringUtils
  location: class com.github.johnthagen.cppcheck.CppcheckInspection
```

Do you build  from Linux where this is an implicitly installed? I think we either need to properly reference this in the build so it's pulled down on any system when we build, or remove this reference (perhaps replacing with a simple implementation of this function ourselves).

After this is resolved, I'll release 1.6.0 (or 1.6.1).

Also, I did a little research and `RandomStringUtils` also appears to be deprecated: https://stackoverflow.com/a/20536590

### PR DESCRIPTION
**Pull request by firewave**
Closes #66

### CODE REVIEW

**Comment by johnthagen** [comment]
@firewave Are you able to check if this builds on Windows under latest IntelliJ IDEA?

**Comment by firewave** [comment]
That's what I am doing. Windows 10 and IDEA 2021.3.1. Possibly another file within the `.idea` folder which needs to be added to the repo.

**Comment by firewave** [comment]
I checked some other plugins and the whole `.idea` folder was missing so there was no project at all after my last changes. This might also explain why I had some trouble getting this to work when I started building it.

**Review by johnthagen — APPROVED** [review]
Builds on Windows 10.

**Comment by johnthagen** [comment]
@firewave I submitted 1.6.1 for moderation. I also opened #69 to track the Gradle migration if you are interested in looking into that, it would be appreciated.

**Comment by johnthagen** [comment]
1.6.1 is now live: https://plugins.jetbrains.com/plugin/8143-cppcheck/versions

**Pull request merged**
