### PR TITLE
Use CapturingProcessHandler to run the cppcheck process

### LINKED ISSUE #13: Problem with path names containing spaces
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): macOS 10.12.6
* IDE Version (e.g. CLion 2016.3.2): CLion 2017.3
* Cppcheck executable version (`cppcheck --version`): 1.81
* Cppcheck plugin version: 1.0.10
* Exact strings used in cppcheck plugin options:
  * **cppcheck path**: /usr/local/bin/cppcheck
  * **cppcheck options**: --enable=all,performance,portability,style --language=c++ --force

### Expected behaviour
Plugin should report the cppcheck warnings even if the path name of the project contains a space
### Actual behaviour
If the path name of the project contains a space, e.g. "/User/myname/Workspace/path with space/projectName" then no error/warnings from cppcheck are shown. Running cppcheck in the CLIon terminal correctly shows them, i..e. cppcheck has no issues with path names containing spaces
### Steps to reproduce the behaviour
create a project in a path name containing paces and some cppcheck error, see that no error/warning is shown. Move the project to a path name without spaces and reopen CLion, then recompile. Errors are shown.

### LINKED ISSUE #15: Release read lock on a write action in EDT
Hi @johnthagen, thank you for the awesome plugin!

There is a performance issue that we observe occasionally in user reports: the annotation thread is waiting for the cppcheck process to finish under a read action. So when the write action is about to happen in the UI thread, it has to wait till the process finish, as the background thread is waiting on [`errorThread.join()`](https://github.com/johnthagen/clion-cppcheck/blob/master/src/com/github/johnthagen/cppcheck/CppcheckInspection.java#L184) and can't be canceled (i.e. by calling `ProgressManager#checkCanceled()`).

I'm attaching the problematic stack trace: [threadDump-20180329-183446.txt](https://github.com/johnthagen/clion-cppcheck/files/1863550/threadDump-20180329-183446.txt)
. You can reproduce this yourself by providing a never-ending executable instead of the cppcheck in the plugin options, forcing it to launch and performing any action that requires write access (i.e. "Reformat file").

The easy fix is to busy-wait for the external process, calling `checkCanceled()` periodically. There is some infrastructure in IntelliJ codebase to help with this, see e.g. https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/sdk/PySdkUtil.java#L153.

Please let me know if you need more information about it.

### PR DESCRIPTION
**Pull request by fastasturtle**
- It allows to kill the process and cancel the inspection pass
  on a pending write action (it would be restarted later)
- It simplifies reading stderr
- Now it kills the external process after a timeout (60s)

This closes #13 and closes #15.

### CODE REVIEW

**Comment by fastasturtle** [comment]
I've tested it lightly on macOS, but I guess some more verification is needed (at least to make sure it works on Windows an Linux).

**Comment by fastasturtle** [comment]
Also is the Travis failure expected? It doesn't seem related to the change (?)

**Comment by johnthagen** [comment]
@fastaturtle The Travis failure is expected, so we can ignore it #6

**Comment by johnthagen** [comment]
I will try it out in Windows, thanks!

**Comment by johnthagen** [comment]
@fastasturtle Do you know if this changes the minimum IntelliJ/CLion version supported by the plugin?

**Comment by fastasturtle** [comment]
> Do you know if this changes the minimum IntelliJ/CLion version supported by the plugin?

It looks like it shouldn't.

**Comment by johnthagen** [comment]
@fastasturtle Tested on Windows and it works, thanks!

**Pull request merged**
