### PR TITLE
some notification cleanups and suppressions of unwanted errors

### PR DESCRIPTION
**Pull request by firewave**

### CODE REVIEW

**Comment by firewave** [comment]
I have one more PR after this one (like the previous ones I will soak this for a few days) and then we should be ready for the 1.6.0 release. 🙂

**Comment by johnthagen** [comment]
>  then we should be ready for the 1.6.0 release

Sounds good. When you're ready for a new release, make a new issue and assign it to me. I'll test out and the do the release.

**Comment by firewave** [comment]
> Sounds good. When you're ready for a new release, make a new issue and assign it to me. I'll test out and the do the release.

I would have just created a PR with the release preparation and version bump in separate commit you could have merged and set the tag on the first one. Can file a ticket as well.

But there might yet be another PR before that - I found another TODO I want to look at first ...

**Comment by johnthagen** [comment]
Yes, if you want to do a PR, that also sounds good.

**Comment by johnthagen** [comment]
@firewave Now that you are a full maintainer, I added a Maintainers section to the README with you included. I think this could make the changelog nicer if we didn't add `(Contribution by @firewave)` to each line. I want you to get credit for your great work, but maybe this way the changelog is a little cleaner? What do you think?

**Comment by firewave** [comment]
> Now that you are a full maintainer, I added a Maintainers section to the README with you included. I think this could make the changelog nicer if we didn't add `(Contribution by @firewave)` to each line. I want you to get credit for your great work, but maybe this way the changelog is a little cleaner? What do you think?

Thanks. That makes sense. I will cleanup the logs when I prepare the release.

**Pull request merged**
