### PR TITLE
Show inconclusive annotation in editor

### LINKED ISSUE #41: No indication a warning is inconclusive
### Environment

* IDE Version (e.g. CLion 2016.3.2): CLion 2020.3 EAP
* Cppcheck executable version (`cppcheck --version`): 2.1
* Cppcheck plugin version: 1.4.2
* Exact strings used in cppcheck plugin options:
  * **cppcheck options**: --enable=all --inconclusive

### Expected behaviour

Warnings tooltips should indicate they are inconclusive.

I ran into analyzing a suspected false negative which turned out to be a inconclusive warning. I could confused since one nstallation showed the warning and one didn't. It turned out one was configured with `--inconclusive`.

### Actual behaviour

image

```
test.cpp:14:22: warning:inconclusive: Access of moved variable 'a'. [accessMoved]
  std::string name = a.s_;
                     ^
test.cpp:13:8: note: Calling std::move(a)
  func(std::move(a));
       ^
test.cpp:14:22: note: $symbol:a
Access of moved variable '$symbol'.
  std::string name = a.s_;
                     ^
```

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #41

Based on work in #42

### CODE REVIEW

**Comment by firewave** [comment]
I could have just rebased my branch and you could have added this as a modification. I wasn't sure about the regex and forget about it at the end... Thanks for that.

**Comment by johnthagen** [comment]
@firewave No worries. I'll credit you all the same. Was just trying to get this moving and be able to test locally. Thanks for the contribution.

**Comment by firewave** [comment]
Nothing to do with credit - just unnecessary to create another PR. But doesn't matter as long as the changes make it to the master. :)

**Comment by johnthagen** [comment]
@firewave This update has been released as the 1.5.0 update. It is awaiting moderation with JetBrains. When that is complete, I will ping you again to have you test in CLion.

**Pull request merged**
