### PR TITLE
fixed compatibility with some products / 1.6.5 release / bumped to 1.6.6

### PR DESCRIPTION
**Pull request by firewave**

### CODE REVIEW

**Review by johnthagen — APPROVED** [review]

**Comment by johnthagen** [comment]
1.6.5 uploaded to JetBrains for moderation.

**Comment by firewave** [comment]
Let's hope three's the charm. 🤞

**Comment by johnthagen** [comment]
1.6.5 is live and it looks good!

**Comment by firewave** [comment]
Yup. Update now showed up.

**Pull request merged**
