### PR TITLE
added commons-lang3 locally (for now) since it is no longer provided by the IDE - fixed #66

### LINKED ISSUE #66: Unable to build 1.6.0 on Windows
@firewave I am unable to build the current `master` branch on Windows with IntelliJ 2021.3. The compile errors I get:

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:14:32
java: package org.apache.commons.lang3 does not exist
```

```
clion-cppcheck\src\com\github\johnthagen\cppcheck\CppcheckInspection.java:57:48
java: cannot find symbol
  symbol:   variable RandomStringUtils
  location: class com.github.johnthagen.cppcheck.CppcheckInspection
```

Do you build  from Linux where this is an implicitly installed? I think we either need to properly reference this in the build so it's pulled down on any system when we build, or remove this reference (perhaps replacing with a simple implementation of this function ourselves).

After this is resolved, I'll release 1.6.0 (or 1.6.1).

Also, I did a little research and `RandomStringUtils` also appears to be deprecated: https://stackoverflow.com/a/20536590

### PR DESCRIPTION
**Pull request by firewave**

### CODE REVIEW

**Comment by firewave** [comment]
I did not test this (yet) and the output seems to match what other plugins are doing.

FYI the plugin still works even without adding the additional JAR - so maybe we don't have to do that.

**Comment by johnthagen** [comment]
@firewave What if we kept it simple and just grabbed a large random number through the Java standard library and used that for the random file name? I feel like they would be cleaner for this small use case rather than vendoring a jar. What do you think?

**Comment by johnthagen** [comment]
I'm thinking something like: https://stackoverflow.com/a/363692 ?

**Comment by johnthagen** [comment]
@firewave Sounds good. Feel free to merge and I'll try again to release a 1.6 buid.

**Pull request merged**
